const ProfilePhotosActionTypes = {
  SET_LIST_OF_PROFILE_PHOTOS: 'SET_LIST_OF_PROFILE_PHOTOS',
  SET_PROFILE: 'SET_PROFILE',
  SET_PHOTOS_COLLECTION: 'SET_PHOTOS_COLLECTION',
  SET_FOLLOWER_COUNT: 'SET_FOLLOWER_COUNT',
};

export default ProfilePhotosActionTypes;
