const uploadActionTypes = {
  SET_OPEN_UPLOAD_MODAL: 'SET_OPEN_UPLOAD_MODAL',
  SET_SELECTED_UPLOAD_FILE: 'SET_SELECTED_UPLOAD_FILE',
  SET_UPLOAD_FILE_LOADING: 'SET_UPLOAD_FILE_LOADING',
};

export default uploadActionTypes;
